import Image from "next/image";
import { RuleDraw } from "@/components/reveal";
import { SectionHead } from "@/components/section-head";
import { MarqueeTrack } from "./marquee-track";
import type { Dictionary } from "@/i18n/dictionaries";

/**
 * Logos are served from /clients/mono — light, monochrome variants generated by
 * inverting each source file's luminance (grayscale + negate), then normalising
 * every mark to the same mean optical weight so none shouts or disappears.
 *
 * Why not a blanket CSS filter: `brightness(0) invert(1)` flattens a mark to its
 * silhouette. Volkswagen's roundel would collapse into a solid disc and lose the
 * monogram; Serangeli's artwork is already white and would turn black. Inverting
 * luminance preserves interior negative space, and Serangeli is passed through
 * untouched — see the generation notes in the design system.
 */
const CLIENTS = [
  { name: "IBM", src: "/clients/mono/ibm.png" },
  { name: "Talke", src: "/clients/mono/talke.png" },
  { name: "Bridgestone", src: "/clients/mono/bridgestone.png" },
  { name: "Rochalog", src: "/clients/mono/rocha.png" },
  { name: "Braskem", src: "/clients/mono/braskem.png" },
  { name: "Volkswagen", src: "/clients/mono/volks.png" },
  { name: "InBetta", src: "/clients/mono/inbetta.png" },
  { name: "Rivelli", src: "/clients/mono/rivelli.png" },
  { name: "SimpleWMS", src: "/clients/mono/simplewms.png" },
  { name: "Serangeli", src: "/clients/mono/serangeli.png" },
  { name: "T-Systems", src: "/clients/mono/tsystems.png" },
  { name: "Coopercitrus", src: "/clients/mono/coopercitrus.png" },
];

const LOOP = [...CLIENTS, ...CLIENTS];

export function ClientsMarquee({ t }: { t: Dictionary }) {
  return (
    <section id="clients" className="section overflow-hidden">
      <div className="shell">
        <div className="grid12">
          <div className="col-span-4 md:col-span-8 lg:col-span-6">
            <SectionHead index="04" kicker={t.clients.eyebrow} title={t.clients.title} lead={t.clients.subtitle} />
          </div>
        </div>
      </div>

      {/* A ruled band, not a row of cards: the same hairlines that run down the
          page become the cell dividers, so the logos sit inside the grid rather
          than on top of it. */}
      <div className="mt-16 md:mt-20">
        <RuleDraw />
        <div className="relative [mask-image:linear-gradient(to_right,transparent,#000_7%,#000_93%,transparent)]">
          <MarqueeTrack>
            {LOOP.map((client, i) => (
              <div
                key={`${client.name}-${i}`}
                className="logo-cell group flex h-[104px] w-[190px] shrink-0 items-center justify-center px-8 sm:w-[220px]"
              >
                <Image
                  src={client.src}
                  alt={`Logo ${client.name}`}
                  width={320}
                  height={80}
                  loading="lazy"
                  className="h-8 w-32 object-contain opacity-55 transition-opacity duration-[320ms] group-hover:opacity-100 sm:w-36"
                />
              </div>
            ))}
          </MarqueeTrack>
        </div>
        <RuleDraw />
      </div>
    </section>
  );
}
